version: '3.5'
services:
  processor:
    container_name: processor
    image: processor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server
      - SERVER_DOWNLOAD_PORT=12345
      - SERVER_QUERY_PORT=12346
      - CLIENT_GREP_RESULTS_PORT=12347
      - SERVER_LISTEN_BACKLOG=5
      - MONITOR_TIME=10
      - GARBAGE_COLLECTOR_TIME=30
    volumes:
      - ./processor/config.json:/config.json:rw
      - ./repositories:/repositories:rw
    networks:
      testing_net:
        ipv4_address: 172.24.125.2

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=processor
      - SERVER_LISTEN_BACKLOG=5
      - SERVER_DOWNLOAD_PORT=12345
      - SERVER_QUERY_PORT=12346
      - SERVER_GREP_RESULTS_PORT=12347
      - CLIENT_DOWNLOAD_PORT=12345
      - CLIENT_QUERY_PORT=12346
    volumes:
      - ./server/config.json:/config.json:rw
    networks:
      testing_net:
        ipv4_address: 172.24.125.3
    depends_on:
      - processor

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    stdin_open: true
    tty: true
    environment:
      - SERVER_HOST=processor
      - SERVER_DOWNLOAD_PORT=12345
      - SERVER_QUERY_PORT=12346
    volumes:
      - ./client/config.json:/config.json:rw
    networks:
      testing_net:
        ipv4_address: 172.24.125.4
    depends_on:
      - server
  # client2:
  #   container_name: client2
  #   image: client:latest
  #   entrypoint: python3 /main.py
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - SERVER_HOST=server
  #     - SERVER_DOWNLOAD_PORT=12345
  #     - SERVER_QUERY_PORT=12346
  #   volumes:
  #     - ./client/config.json:/config.json:rw
  #   networks:
  #     testing_net:
  #       ipv4_address: 172.24.125.5
  #   depends_on:
  #     - server

networks:
  testing_net:
    name: testing_net
    ipam:
      driver: default
      config:
        - subnet: 172.24.125.0/16